easy_admin:
    site_name: 'Arealudvikling Aarhus'
#    site_name: '<img src="/logos/symfony_white_01.png" /> Arealudvikling Aarhus'

    list:
        max_results: 100

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
#        number: '%.0f'

    design:
        brand_color: '#157fcc'
        color_scheme: 'light'

        templates:
            layout: '@App/EasyAdmin/layout.html.twig'

        menu:
            - label: 'Parcelhusgrunde'
              icon: 'home'
              children:
                - { entity: 'vis_parcelhusgrunde', label: 'Vis Parcelhusgrunde' }
                - { entity: 'parcelhusgrunde', label: 'Alle Parcelhusgrunde' }


    # http://stackoverflow.com/questions/8466223/reuse-a-block-of-code-in-yaml

    entities:
        parcelhusgrunde:
            class: AppBundle\Entity\Grund
            controller: AppBundle\Controller\GrundController
            templates:
                # Twig namespace template syntax
                list: '@App/EasyAdmin/list.html.twig'
                edit: '@App/EasyAdmin/grund.html.twig'
            list:
                title: 'Parcelhusgrunde'
                sort: postby
                dql_filter: entity.grundtype = 'Parcelhusgrund'
#                dql_filter: entity.grundtype = 'Parcelhusgrund' AND (entity.status='Ledig' OR entity.status='Annonceret') and entity.salgstatus= 'Ledig'
                fields:
                    - vej
                    - {property: husnummer, css_class: 'text-right', format: '%.0f' }
                    - {property: postby.postalcode, css_class: 'text-right'}
                    - postby.city
                    - { property: 'annonceres' }
                    - salgsomraade.titel
                    - salgsomraade.lokalplan.nr
                    - salgstype
                    - {property: areal, css_class: 'text-right', format: '%.0f' }
                    - {property: pris, css_class: 'text-right' }
            edit:
                title: 'Ny Grund'

            form:
                fields: '%fields%'

        vis_parcelhusgrunde:
            class: AppBundle\Entity\Grund
            controller: AppBundle\Controller\GrundController

            form:
                fields: '%fields%'