# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  symfony.controller.subscriber.init:
    class: Yavin\Symfony\Controller\InitControllerSubscriber
    tags:
      - { name: kernel.event_subscriber }

  grundsalg.communication:
    class: AppBundle\Service\GrundsalgCommunicationService
    arguments: ['%grundsalg_web%']

  app.timestampable_subscriber:
    class: AppBundle\EventSubscriber\TimestampableSubscriber
    tags:
      - { name: doctrine.event_subscriber }
