# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  grundsalg.communication:
    class: AppBundle\Service\GrundsalgCommunicationService
    arguments: ['%grundsalg_web%']

  app.salgsomraade_subscriber:
    class: AppBundle\EventSubscriber\SalgsomraadeCommunicationSubscriber
    tags:
      - { name: doctrine.event_subscriber }
    arguments: [ '@grundsalg.communication' ]

  app.calculation.salgsomraade:
    class: AppBundle\CalculationService\SalgsomraadeCalculator
    tags:
      - { name: doctrine.event_subscriber }
    arguments: [ '@doctrine.orm.entity_manager' ]

  app.calculation.grund:
    class: AppBundle\CalculationService\GrundCalculator
    tags:
      - { name: doctrine.event_subscriber }
    arguments: [ '@doctrine.orm.entity_manager' ]