# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  grundsalg.communication:
    class: AppBundle\Service\GrundsalgCommunicationService
    arguments: ['%grundsalg_web%']

  app.salgsomraade_subscriber:
    class: AppBundle\EventSubscriber\SalgsomraadeSubscriber
    tags:
      - { name: doctrine.event_subscriber }
    arguments: [ '@grundsalg.communication' ]

  app.timestampable_subscriber:
    class: AppBundle\EventSubscriber\TimestampableSubscriber
    tags:
      - { name: doctrine.event_subscriber }

  app.report_manager:
    class: AppBundle\Report\Manager
    arguments:
      - reports:
          - class: AppBundle\Report\ReportTilSalgIPerioden
          - class: AppBundle\Report\ReportOekonomi
          - class: AppBundle\Report\ReportOpkoebOgForbrug
