# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  symfony.controller.subscriber.init:
    class: Yavin\Symfony\Controller\InitControllerSubscriber
    tags:
      - { name: kernel.event_subscriber }

  trans_key_extension:
    class: AppBundle\Twig\Extension\TransKeyExtension
    arguments: ['@translator']
    tags:
      - {name: "twig.extension"}

  grundsalg.communication:
    class: AppBundle\Service\GrundsalgCommunicationService
    arguments: ['%grundsalg_web%']