# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: php:7.1-apache
        environment:
          APP_ENV: circleci

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
#      - image: circleci/mysql:latest

    working_directory: /var/www/html

    steps:
      - run:
          name: Apt-get update
          command: apt-get update && apt-get install -y zlib*

      - run:
          name: Install PHP extensions - zip
          command: docker-php-ext-install zip && docker-php-ext-enable zip

      - run:
          name: Install PHP extensions - pdo_mysql
          command: docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql

      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"

      - run: php composer.phar install --no-interaction

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: vendor/bin/behat