easy_admin:
    entities:
        landinspektoer:
            class: AppBundle\Entity\Landinspektoer
            controller:
            list:
                title: 'Landinspektør'
                sort: ['navn', 'ASC']
                actions:
                    <<: *default_list_actions
                fields:
                    - { property: active, label: 'Aktiv' }
                    - { property: navn }
                    - { property: email }
                    - { property: telefon }

            edit:
                title: 'Rediger Landinspektør'

            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12 new-row', label: 'Landinspektør' }
                    - { property: active, label: 'Aktiv' }
                    - { property: navn }
                    - { property: adresse }
                    - { property: postby, label: 'Postnr/By' }
                    - { property: telefon }
                    - { property: mobil }
                    - { property: email }
                    - { type: 'divider' }
                    - { property: notat }
