easy_admin:
    entities:
        landinspektoer:
            class: AppBundle\Entity\Landinspektoer
            controller:
            list:
                title: 'Landinspektører'
                sort: ['navn', 'ASC']
                fields:
                    - { property: active, label: 'Aktiv' }
                    - { property: navn }
                    - { property: email }
                    - { property: telefon }

            search:
                fields:
                    - navn
                    - email
                    - telefon

            edit:
                roles: [ROLE_ADMIN]
                title: 'Rediger Landinspektør'

            new:
                roles: [ROLE_ADMIN]
                title: 'Opret Landinspektør'

            form:
                fields: &landinspektoer_form_fields
                    - { type: 'group', css_class: 'col-sm-12 new-row', label: 'Landinspektør' }
                    - { property: active, label: 'Aktiv' }
                    - { property: navn }
                    - { property: adresse }
                    - { property: postby, label: 'Postnr/By' }
                    - { property: telefon }
                    - { property: mobil }
                    - { property: email }
                    - { type: 'divider' }
                    - { property: notat }

            show:
                title: 'Landinspektør'
                fields:
                    <<: *landinspektoer_form_fields