easy_admin:
    entities:
        lokalsamfund:
            class: AppBundle\Entity\Lokalsamfund
            controller:
            list:
                title: 'Lokalsamfund'
                sort: ['name', 'ASC']
                actions: ['edit', 'search', '-delete']
                fields:
                    - { property: active, label: 'Aktiv' }
                    - { property: number, label: 'Nr.', css_class: 'text-right', format: '%.0f' }
                    - { property: name, label: 'Navn' }

            edit:
                title: 'Rediger Lokalsamfund'

            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12 new-row', label: 'Lokalsamfund' }
                    - { property: active, label: 'Aktiv' }
                    - { property: number, label: 'Nr.' }
                    - { property: name, label: 'Navn' }

                    - { type: 'group', css_class: 'col-sm-12 new-row', label: 'Redigeret' }
                    - { property: 'createdBy', type: 'text', css_class: 'col-sm-6', readonly: true, type_options: { disabled: true } }
                    - { property: 'updatedBy', type: 'text', css_class: 'col-sm-6', readonly: true, type_options: { disabled: true } }
                    - { property: 'createdAt', type: 'date', css_class: 'col-sm-6', readonly: true, type_options: { disabled: true, widget: 'single_text' } }
                    - { property: 'updatedAt', type: 'date', css_class: 'col-sm-6', readonly: true, type_options: { disabled: true, widget: 'single_text' } }