easy_admin:
    entities:
        interessent:
            class: AppBundle\Entity\Interessent
            controller:
            list:
                title: 'Interessenter'
                sort: [koeberNavn, 'ASC']
                actions:
                    - { name: -new }
                dql_filter: (entity.koeberNavn IS NOT NULL AND entity.koeberNavn != '')
                            OR (entity.koeberAdresse IS NOT NULL AND entity.koeberAdresse != '')
                            OR (entity.koeberLand IS NOT NULL AND entity.koeberLand != '')
                            OR (entity.koeberTelefon IS NOT NULL AND entity.koeberTelefon != '')
                            OR (entity.koeberMobil IS NOT NULL AND entity.koeberMobil != '')
                            OR (entity.koeberEmail IS NOT NULL AND entity.koeberEmail != '')
                            OR (entity.koeberNotat IS NOT NULL AND entity.koeberNotat != '')
                fields:
                    - { property: koeberNavn, label: 'app.grund.koeber' }
                    - { property: koeberAdresse, label: 'app.grund.koeberAdresse' }
                    - { property: koeberLand, label: 'app.grund.koeberLand' }
                    - { property: koeberTelefon, label: 'app.grund.koeberTelefon' }
                    - { property: koeberMobil, label: 'app.grund.koeberMobil' }
                    - { property: koeberEmail, label: 'app.grund.koeberEmail' }

            search:
                fields:
                    - koeberNavn
                    - koeberAdresse
                    - koeberLand
                    - koeberTelefon
                    - koeberMobil
                    - koeberEmail
                    - koeberNotat
                    - note
                    - medkoeberNavn
                    - medkoeberAdresse
                    - medkoeberLand
                    - medkoeberTelefon
                    - medkoeberMobil
                    - medkoeberEmail

            form:
                fields: &interessent_form_fields
                    - { type: 'group', css_class: 'col-md-6', label: 'app.interessent.koeber' }
                    - { property: koeberNavn, label: 'app.grund.koeberNavn' }
                    - { property: koeberAdresse, label: 'app.grund.koeberAdresse' }
                    - { property: koeberPostby, label: 'app.grund.koeberPostby' }
                    - { property: koeberLand, label: 'app.grund.koeberLand' }
                    - { property: koeberTelefon, label: 'app.grund.koeberTelefon' }
                    - { property: koeberMobil, label: 'app.grund.koeberMobil' }
                    - { property: koeberEmail, label: 'app.grund.koeberEmail' }

                    - { type: 'group', css_class: 'col-md-6', label: 'app.interessent.medkoeber' }
                    - { property: medkoeberNavn, label: 'app.grund.medkoeberNavn' }
                    - { property: medkoeberAdresse, label: 'app.grund.medkoeberAdresse' }
                    - { property: medkoeberPostby, label: 'app.grund.medkoeberPostby' }
                    - { property: medkoeberLand, label: 'app.grund.medkoeberLand' }
                    - { property: medkoeberTelefon, label: 'app.grund.medkoeberTelefon' }
                    - { property: medkoeberMobil, label: 'app.grund.medkoeberMobil' }
                    - { property: medkoeberEmail, label: 'app.grund.medkoeberEmail' }

                    - { type: 'group', css_class: 'col-xs-12', label: 'app.interessent.notat' }
                    - { property: koeberNotat, label: 'app.interessent.notat' }

            edit:
                roles: [ROLE_EDITOR]
                title: 'Rediger Interessent'
                actions:
                    - { name: -delete }
                    - { name: 'interessent_cancel', type: 'route', icon: 'minus-square', css_class: 'btn btn_default', label: 'Annuller venteliste' }

            show:
                title: 'Interessent'
                actions:
                    - { name: -delete }

                fields:
                    - { type: 'group', css_class: 'col-md-6', label: 'app.interessent.koeber' }
                    - { property: koeberNavn, label: 'app.grund.koeberNavn' }
                    - { property: koeberAdresse, label: 'app.grund.koeberAdresse' }
                    - { property: koeberPostby, label: 'app.grund.koeberPostby' }
                    - { property: koeberLand, label: 'app.grund.koeberLand' }
                    - { property: koeberTelefon, label: 'app.grund.koeberTelefon' }
                    - { property: koeberMobil, label: 'app.grund.koeberMobil' }
                    - { property: koeberEmail, label: 'app.grund.koeberEmail' }

                    - { type: 'group', css_class: 'col-md-6', label: 'app.interessent.medkoeber' }
                    - { property: medkoeberNavn, label: 'app.grund.medkoeberNavn' }
                    - { property: medkoeberAdresse, label: 'app.grund.medkoeberAdresse' }
                    - { property: medkoeberPostby, label: 'app.grund.medkoeberPostby' }
                    - { property: medkoeberLand, label: 'app.grund.medkoeberLand' }
                    - { property: medkoeberTelefon, label: 'app.grund.medkoeberTelefon' }
                    - { property: medkoeberMobil, label: 'app.grund.medkoeberMobil' }
                    - { property: medkoeberEmail, label: 'app.grund.medkoeberEmail' }

                    - { type: 'group', css_class: 'col-xs-12', label: 'app.interessent.notat' }
                    - { property: koeberNotat, label: 'app.interessent.notat' }

                    - { type: 'group', css_class: 'col-xs-12', label: 'app.interessent.venteliste' }
                    - { property: reservationer, label: 'app.interessent.reservationer' }


