easy_admin:

    # http://stackoverflow.com/questions/8466223/reuse-a-block-of-code-in-yaml

    entities:
        grund_collection:
            roles: [ROLE_EDITOR]
            class: AppBundle\Entity\GrundCollection

            new:
                title: 'Opret Grunde (flere)'

            form:
                # Note: The custom edit template used overrides/ignores some of EasyAdmins config features
                fields:
                    - { type: 'group', css_class: 'col-sm-12 new-row', label: 'Salgsomraade' }
                    - { property: 'salgsomraade', label: 'app.grund.salgsomraade', css_class: 'col-sm-6' }

                    - { type: 'group', label: 'Grund', css_class: 'col-sm-6' }
                    - { property: 'type', label: 'app.grund.type', type: 'AppBundle\Form\Field\GrundType' }
                    - { property: 'ejerlav', label: 'app.grund.ejerlav' }
                    - { property: 'vej', label: 'app.grund.vej' }
                    - { property: 'postby', label: 'app.grund.postby' }
                    - { property: 'lokalsamfund', label: 'app.grund.lokalsamfund' }
                    - { property: 'landinspektoer', label: 'app.grund.landinspektoer' }
                    - { property: 'prism2', label: 'app.grund.prism2' }
                    - { property: 'urlgis', label: 'app.grund.urlgis', type: url }

                    - { type: 'group', label: 'Salg', css_class: 'col-sm-6' }
                    - { property: 'visStatus', label: 'app.grund.salgstatus', type: 'text', , readonly: true, type_options: { disabled: true } }
                    - { property: 'salgstype', label: 'app.grund.salgstype', type: 'AppBundle\Form\Field\SalgsType' }
                    - { property: 'annonceres', label: 'app.grund.annonceres' }
                    - { property: 'datoAnnonce', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.datoAnnonce' }
                    - { property: 'datoAnnonce1', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.datoAnnonce1' }
                    - { property: 'tilsluttet', label: 'app.grund.tilsluttet', type: 'AppBundle\Form\Field\TilslutningsType', type_options: { expanded : true, multiple : true } }

                    - { type: 'group', label: 'Salg', css_class: 'col-sm-12 new-row' }
                    - property: grunde
                      type: collection
                      label: false
                      type_options:
                        entry_type: AppBundle\Form\Type\MultiGrundEmbedType
                        block_name: grunde_list
                        by_reference: false
                        required: true
                      embedded: true
