easy_admin:

    # http://stackoverflow.com/questions/8466223/reuse-a-block-of-code-in-yaml

    entities:
        grund_collection:
            roles: [ROLE_EDITOR]
            templates: &default_andregrund_templates
                # Twig namespace template syntax
                new: 'easy_admin/grund/collection.html.twig'
            class: AppBundle\Entity\GrundCollection
            disabled_actions: ['edit', 'delete']

            new:
                title: 'Opret Grunde (flere)'

            form:
                # Note: The custom edit template used overrides/ignores some of EasyAdmins config features
                fields:
                    - { type: 'group', css_class: 'col-sm-12 new-row', label: 'Salgsomraade' }
                    - { property: 'salgsomraade', label: 'app.grund.salgsomraade', css_class: 'col-sm-6' }

                    - { property: 'ejerlav', label: 'app.grund.ejerlav' }
                    - { property: 'vej', label: 'app.grund.vej' }
                    - { property: 'prism2', label: 'app.grund.prism2' }

                    - { property: 'status', label: 'app.grund.status', type: 'AppBundle\Form\Field\GrundStatus' }
                    - { property: 'salgstype', label: 'app.grund.salgstype', type: 'AppBundle\Form\Field\SalgsType' }
                    - { property: 'annonceres', label: 'app.grund.annonceres' }
                    - { property: 'datoannonce', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.datoannonce' }
                    - { property: 'datoannonce1', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.datoannonce1' }
                    - { property: 'tilsluttet', label: 'app.grund.tilsluttet', type: 'AppBundle\Form\Field\TilslutningsType', type_options: { expanded : true, multiple : true } }

                    - { property: 'auktionstartdato', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.auktionstartdato' }
                    - { property: 'auktionslutdato', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.auktionslutdato' }

                    - { type: 'group', label: 'Salg', css_class: 'col-sm-12 new-row' }
                    - property: grunde
                      type: collection
                      label: false
                      type_options:
                        entry_type: AppBundle\Form\Type\MultiGrundEmbedType
                        block_name: grunde_list
                        by_reference: false
                        required: true
                      embedded: true
