easy_admin:

    # http://stackoverflow.com/questions/8466223/reuse-a-block-of-code-in-yaml

    entities:
        parcelhusgrund: &parcelhusgrund_default
            class: AppBundle\Entity\Grund
            templates: &default_parcelhus_templates
                # Twig namespace template syntax
                list: 'easy_admin/list.html.twig'
                edit: 'easy_admin/grund/edit.html.twig'
                show: 'easy_admin/grund/show.html.twig'
                new: 'easy_admin/grund/new.html.twig'
            list: &parcelhusgrund_default_list
                title: 'Alle Parcelhusgrunde'
                sort: ['vej', 'ASC']
                dql_filter: entity.type = 'Parcelhusgrund'
                actions:
                    <<: *default_list_actions

                fields:
                    - { property: vej, label: 'app.grund.vej' }
                    - { property: husnummer, label: 'app.grund.husnummer', css_class: 'text-right', format: '%.0f' }
                    - { property: postby.postalcode, css_class: 'text-right', label: 'app.postby.postalcode' }
                    - { property: postby.city, label: 'app.postby.city' }
                    - { property: annonceres, label: 'app.grund.annonceres' }
                    - { property: salgsomraade.titel, label: 'app.grund.salgsomraade' }
                    - { property: salgsomraade.lokalplan.nr, label: 'app.lokalplan.nr' }
                    - { property: salgstype, label: 'app.grund.salgstype' }
                    - { property: areal, label: 'app.grund.areal', css_class: 'text-right', format: '%.0f' }
                    - { property: pris, label: 'app.grund.pris', css_class: 'text-right' }

            delete:
                roles: [ROLE_EDITOR]

            search: &parcelhusgrund_default_search
                fields:
                    - vej
                    - husnummer
                    - postby.postalcode
                    - postby.city
                    - salgsomraade.titel
                    - salgsomraade.lokalplan.nr
                    - salgstype
                    - areal
                    - pris

            edit: &parcelhusgrund_default_edit
                roles: [ROLE_EDITOR]
                title: 'Rediger Parcelhusgrund'
                actions:
                    - { name: delete, roles: [ROLE_ADMIN] }

            show: &parcelhusgrund_default_show
                title: 'Parcelhusgrund'
                actions:
                    - { name: edit, roles: [ROLE_EDITOR] }
                    - { name: delete, roles: [ROLE_ADMIN] }

            new: &parcelhusgrund_default_new
                title: 'Opret Grund'

            form: &parcelhusgrund_default_form
                # Note: The custom edit template used overrides/ignores some of EasyAdmins config features
                fields:
                    - { property: 'salgsomraade', label: 'app.grund.salgsomraade' }

                    - { property: 'landinspektoer', label: 'app.grund.landinspektoer' }

                    - { property: 'mnr', label: 'app.grund.mnr' }
                    - { property: 'mnr2', label: 'app.grund.mnr2' }
                    - { property: 'delareal', label: 'app.grund.delareal' }
                    - { property: 'ejerlav', label: 'app.grund.ejerlav' }
                    - { property: 'vej', label: 'app.grund.vej' }
                    - { property: 'husnummer', label: 'app.grund.husnummer' }
                    - { property: 'bogstav', label: 'app.grund.bogstav' }
                    - { property: 'postby', label: 'app.grund.postby' }
                    - { property: 'lokalsamfund', label: 'app.grund.lokalsamfund' }

                    - { property: 'status', label: 'app.grund.status', type: 'AppBundle\Form\Field\GrundStatus' }
                    - { property: 'publicstatus', label: 'app.grund.publicstatus', type: 'AppBundle\Form\Field\GrundPublicStatus' }
                    - { property: 'annonceres', label: 'app.grund.annonceres' }
                    - { property: 'datoAnnonce', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.datoAnnonce' }
                    - { property: 'datoAnnonce1', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.datoAnnonce1' }

                    - { property: 'auktionstartdato', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.auktionstartdato' }
                    - { property: 'auktionslutdato', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.auktionslutdato' }

                    - { property: 'type', label: 'app.grund.type', type: 'AppBundle\Form\Field\GrundType' }
                    - { property: 'salgstype', label: 'app.grund.salgstype', type: 'AppBundle\Form\Field\SalgsType' }
                    - { property: 'tilsluttet', label: 'app.grund.tilsluttet', type: 'AppBundle\Form\Field\TilslutningsType', type_options: { expanded : true, multiple : true } }

                    - { property: 'maxetagem2', label: 'app.grund.maxetagem2' }
                    - { property: 'areal', label: 'app.grund.areal' }
                    - { property: 'arealvej', label: 'app.grund.arealvej' }
                    - { property: 'arealkotelet', label: 'app.grund.arealkotelet' }
                    - { property: 'bruttoareal', label: 'app.grund.bruttoareal' }
                    - { property: 'prism2', label: 'app.grund.prism2' }
                    - { property: 'pris', label: 'app.grund.pris' }
                    - { property: 'fastpris', label: 'app.grund.fastpris' }
                    - { property: 'minbud', label: 'app.grund.minbud' }

                    - { property: 'priskorrektion1', label: 'app.grund.priskorrektion1', type: 'AppBundle\Form\Field\Priskorrektion' }
                    - { property: 'antalkorr1', label: 'app.grund.antalkorr1' }
                    - { property: 'akrkorr1', label: 'app.grund.akrkorr1' }
                    - { property: 'priskorrektion2', label: 'app.grund.priskorrektion2', type: 'AppBundle\Form\Field\Priskorrektion' }
                    - { property: 'antalkorr2', label: 'app.grund.antalkorr2' }
                    - { property: 'akrkorr2', label: 'app.grund.akrkorr2' }
                    - { property: 'priskorrektion3', label: 'app.grund.priskorrektion3', type: 'AppBundle\Form\Field\Priskorrektion' }
                    - { property: 'antalkorr3', label: 'app.grund.antalkorr3' }
                    - { property: 'akrkorr3', label: 'app.grund.akrkorr3' }

                    - { property: 'note', label: 'app.grund.note' }

                    - { property: 'resstart', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.resstart' }
                    - { property: 'resslut', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.resslut' }
                    - { property: 'tilbudstart', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.tilbudstart' }
                    - { property: 'tilbudslut', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.tilbudslut' }
                    - { property: 'accept', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.accept' }
                    - { property: 'overtagelse', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.overtagelse' }
                    - { property: 'skoederekv', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.skoederekv' }
                    - { property: 'beloebanvist', type: 'date', type_options: { widget: 'single_text' }, label: 'app.grund.beloebanvist' }
                    - { property: 'salgsprisumoms', label: 'app.grund.salgsprisumoms' }
                    - { property: 'antagetbud', label: 'app.grund.antagetbud' }

                    - { property: 'koeberNavn', label: 'app.grund.koeberNavn' }
                    - { property: 'koeberAdresse', label: 'app.grund.koeberAdresse' }
                    - { property: 'koeberPostby', label: 'app.grund.koeberPostby' }
                    - { property: 'koeberLand', label: 'app.grund.koeberLand' }
                    - { property: 'koeberTelefon', label: 'app.grund.koeberTelefon' }
                    - { property: 'koeberMobil', label: 'app.grund.koeberMobil' }
                    - { property: 'koeberEmail', label: 'app.grund.koeberEmail' }

                    - { property: 'medkoeberNavn', label: 'app.grund.medkoeberNavn' }
                    - { property: 'medkoeberAdresse', label: 'app.grund.medkoeberAdresse' }
                    - { property: 'medkoeberPostby', label: 'app.grund.medkoeberPostby' }
                    - { property: 'medkoeberLand', label: 'app.grund.medkoeberLand' }
                    - { property: 'medkoeberTelefon', label: 'app.grund.medkoeberTelefon' }
                    - { property: 'medkoeberMobil', label: 'app.grund.medkoeberMobil' }
                    - { property: 'medkoeberEmail', label: 'app.grund.medkoeberEmail' }

                    - { property: 'koeberNotat', label: 'app.grund.koeberNotat' }

        vis_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Vis Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND (entity.status='Ledig' OR entity.status='Annonceret') and entity.salgstatus= 'Ledig'

                # Import default values
                <<: *parcelhusgrund_default_list

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        fremtidige_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Fremtidige Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND (entity.status='Fremtidig')

                # Import default values
                <<: *parcelhusgrund_default_list

                # Inspired by https://github.com/javiereguiluz/EasyAdminBundle/issues/1503#issuecomment-276128125
                bulk: &parcelhusgrund_bulk
                    roles: [ROLE_EDITOR]
                    actions:
                        - label: Flyt til ledige grunde
                          # title: Update status – or not!
                          # message: Vælg ny status.
                          type: form
                          form:
                              block_name: data # field block name
                              action:
                                  label: Flyt grunde
                                  value: update-status
                                  route: bulk_update
                              close:
                                  label: Cancel
                              fields:
                                  - name: status
                                    type: hidden
                                    type_options:
                                        data: !php/const:AppBundle\DBAL\Types\GrundStatus::LEDIG
                                  - name: salgstatus
                                    type: hidden
                                    type_options:
                                        data: !php/const:AppBundle\DBAL\Types\GrundSalgStatus::LEDIG

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        annoncerede_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Annoncerede Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND (entity.status='Annonceret')

                # Import default values
                <<: *parcelhusgrund_default_list
                bulk: *parcelhusgrund_bulk

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        auktionslut_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Auktion slut Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND entity.status='Auktion slut' AND entity.salgstatus != 'Solgt' AND entity.salgstatus != 'Accepteret' AND entity.salgstatus != 'Skøde rekvireret' AND entity.salgstatus != 'Skøde annulleret'

                # Import default values
                <<: *parcelhusgrund_default_list
                bulk: *parcelhusgrund_bulk

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        ledige_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Ledige Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND entity.status='Ledig' AND (entity.salgstatus IS NULL OR entity.salgstatus = 'Ledig')

                # Import default values
                <<: *parcelhusgrund_default_list

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        tilbud_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Tilbud Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND entity.status='Ledig' AND (entity.salgstatus = 'Reserveret' OR entity.salgstatus = 'Reservation annulleret' OR entity.salgstatus = 'Tilbud sendt' OR entity.salgstatus = 'Tilbud annulleret')

                # Import default values
                <<: *parcelhusgrund_default_list

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        accepterede_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Accepterede Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND (entity.status='Ledig' OR entity.status='Auktion Slut') AND (entity.salgstatus = 'Accepteret' OR entity.salgstatus = 'Skøde rekvireret' OR entity.salgstatus = 'Skøde annulleret')

                # Import default values
                <<: *parcelhusgrund_default_list

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form

        betalte_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Betalte Parcelhusgrunde'
                dql_filter: entity.type = 'Parcelhusgrund' AND entity.salgstatus = 'Solgt'

                fields:
                    - { property: vej, label: 'app.grund.vej' }
                    - { property: husnummer, label: 'app.grund.husnummer', css_class: 'text-right', format: '%.0f' }
                    - { property: postby.postalcode, css_class: 'text-right', label: 'app.postby.postalcode' }
                    - { property: postby.city, label: 'app.postby.city' }
                    - { property: koeberNavn, label: 'app.grund.koeberNavn' }
                    - { property: koeberAdresse, label: 'app.grund.koeberAdresse.list' }
                    - { property: annonceres, label: 'app.grund.annonceres' }
                    - { property: salgsomraade.titel, label: 'app.grund.salgsomraade' }
                    - { property: salgsomraade.lokalplan.nr, label: 'app.lokalplan.nr' }
                    - { property: salgstype, label: 'app.grund.salgstype' }
                    - { property: areal, label: 'app.grund.areal', css_class: 'text-right', format: '%.0f' }
                    - { property: pris, label: 'app.grund.pris', css_class: 'text-right' }

                # Import default values
                <<: *parcelhusgrund_default_list

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form


        opfoelgning_parcelhusgrund:
            class: AppBundle\Entity\Grund
            templates: *default_parcelhus_templates

            list:
                title: 'Opfølgning'
                dql_filter: entity.type = 'Parcelhusgrund' AND ((entity.salgstatus = 'Reserveret' AND entity.resslut < CURRENT_DATE()) OR (entity.salgstatus = 'Tilbud sendt' AND entity.tilbudslut < CURRENT_DATE()))

                # Import default values
                <<: *parcelhusgrund_default_list

            search: *parcelhusgrund_default_search
            edit: *parcelhusgrund_default_edit
            show: *parcelhusgrund_default_show
            new: *parcelhusgrund_default_new
            form: *parcelhusgrund_default_form
