easy_admin:
    site_name: 'Arealudvikling Aarhus'
#    site_name: '<img src="/logos/symfony_white_01.png" /> Arealudvikling Aarhus'

    list:
        max_results: 100
        actions: &default_list_actions
            - { name: edit, css_class: 'btn btn-default' }
            - { name: search }
            - { name: new, label: 'Tilføj', icon: 'plus' }
            - { name: -delete }

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
#        number: '%.0f'
