easy_admin:
    site_name: 'Arealudvikling Aarhus'

    list:
        max_results: 100
        actions: &default_list_actions
            - { name: show, css_class: 'btn btn-default' }
            - { name: edit, css_class: 'btn btn-default', roles: [ROLE_ADMIN] }
            - { name: search }
            - { name: new, label: 'Tilføj', icon: 'plus', roles: [ROLE_ADMIN] }
            - { name: -delete }

    show: &default_show_actions
        actions:
            - { name: edit, roles: [ROLE_ADMIN] }
            - { name: delete, roles: [ROLE_ADMIN] }

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
