easy_admin:
    design:
        brand_color: '#157fcc'
        color_scheme: 'light'
        form_theme: 'easy_admin/form/bootstrap_3_horizontal_layout.html.twig'
#        form_theme: 'easy_admin/form/bootstrap_3_layout.html.twig'

        templates:
            layout: 'easy_admin/layout.html.twig'

        assets:
            css:
                - '/css/grundsalg-styles.css'

        menu:
            - label: 'Parcelhusgrunde'
              icon: 'home'
              children:
                - { entity: 'vis_parcelhusgrund', label: 'Vis Parcelhusgrunde' }
                - { entity: 'fremtidige_parcelhusgrund', label: 'Fremtidige Parcelhusgrunde' }
                - { entity: 'annoncerede_parcelhusgrund', label: 'Annoncerede Parcelhusgrunde' }
                - { entity: 'auktionslut_parcelhusgrund', label: 'Auktion Slut Parcelhusgrunde' }
                - { entity: 'ledige_parcelhusgrund', label: 'Ledige Parcelhusgrunde' }
                - { entity: 'tilbud_parcelhusgrund', label: 'Tilbud Parcelhusgrunde' }
                - { entity: 'accepterede_parcelhusgrund', label: 'Accepterede Parcelhusgrunde' }
                - { entity: 'betalte_parcelhusgrund', label: 'Betalte Parcelhusgrunde' }
                - { entity: 'parcelhusgrund', label: 'Alle Parcelhusgrunde' }
                - { entity: 'opfoelgning_parcelhusgrund', label: 'Opfølgning' }
            - label: 'Storparceller'
              icon: 'sitemap'
              children:
                - { entity: 'vis_storparcel', label: 'Vis Storparceller' }
                - { entity: 'fremtidige_storparcel', label: 'Fremtidige Storparceller' }
                - { entity: 'annoncerede_storparcel', label: 'Annoncerede Storparceller' }
                - { entity: 'auktionslut_storparcel', label: 'Auktion Slut Storparceller' }
                - { entity: 'ledige_storparcel', label: 'Ledige Storparceller' }
                - { entity: 'tilbud_storparcel', label: 'Tilbud Storparceller' }
                - { entity: 'accepterede_storparcel', label: 'Accepterede Storparceller' }
                - { entity: 'betalte_storparcel', label: 'Betalte Storparceller' }
                - { entity: 'storparcel', label: 'Alle Storparceller' }
                - { entity: 'opfoelgning_storparcel', label: 'Opfølgning' }
            - label: 'Erhvervsgrunde'
              icon: 'industry'
              children:
                - { entity: 'vis_erhvervsgrund', label: 'Vis Erhvervsgrunde' }
                - { entity: 'fremtidige_erhvervsgrund', label: 'Fremtidige Erhvervsgrunde' }
                - { entity: 'annoncerede_erhvervsgrund', label: 'Annoncerede Erhvervsgrunde' }
                - { entity: 'auktionslut_erhvervsgrund', label: 'Auktion Slut Erhvervsgrunde' }
                - { entity: 'ledige_erhvervsgrund', label: 'Ledige Erhvervsgrunde' }
                - { entity: 'tilbud_erhvervsgrund', label: 'Tilbud Erhvervsgrunde' }
                - { entity: 'accepterede_erhvervsgrund', label: 'Accepterede Erhvervsgrunde' }
                - { entity: 'betalte_erhvervsgrund', label: 'Betalte Erhvervsgrunde' }
                - { entity: 'erhvervsgrund', label: 'Alle Erhvervsgrunde' }
                - { entity: 'opfoelgning_erhvervsgrund', label: 'Opfølgning' }
            - label: 'Andre Grunde'
              icon: 'building'
              children:
                - { entity: 'vis_andregrund', label: 'Vis Andre Grunde' }
                - { entity: 'fremtidige_andregrund', label: 'Fremtidige Andre Grunde' }
                - { entity: 'annoncerede_andregrund', label: 'Annoncerede Andre Grunde' }
                - { entity: 'auktionslut_andregrund', label: 'Auktion Slut Andre Grunde' }
                - { entity: 'ledige_andregrund', label: 'Ledige Andre Grunde' }
                - { entity: 'tilbud_andregrund', label: 'Tilbud Andre Grunde' }
                - { entity: 'accepterede_andregrund', label: 'Accepterede Andre Grunde' }
                - { entity: 'betalte_andregrund', label: 'Betalte Andre Grunde' }
                - { entity: 'andregrund', label: 'Alle Andre Grunde' }
                - { entity: 'opfoelgning_andregrund', label: 'Opfølgning' }
            - label: 'Lokalplaner m.v.'
              icon: 'map'
              children:
                - { entity: 'lokalplan', label: 'Lokalplaner' }
                - { entity: 'delomraade', label: 'Delområder' }
                - { entity: 'salgsomraade', label: 'Salgsområder' }
                - { entity: 'opkoeb', label: 'Opkøb' }
            - label: 'Admin'
              icon: 'wrench'
              children:
                - { entity: 'postby', label: 'Postnr / By' }
                - { entity: 'landinspektoer', label: 'Landinspektør' }
                - { entity: 'lokalsamfund', label: 'Lokalsamfund' }
                - { entity: 'user', label: 'Brugere' }
            - label: 'Statistik'
              icon: 'bar-chart'
              children:
                - { label: 'Betalte i alt' }
                - { label: 'Betalte Parcelhusgrunde', route: 'grundsalg_statistics_betalte_overview', params: { type: 'Parcelhusgrund' } }
                - { label: 'Betalte Storparceller', route: 'grundsalg_statistics_betalte_overview', params: { type: 'Storparcel' } }
                - { label: 'Betalte Erhvervsgrunde', route: 'grundsalg_statistics_betalte_overview', params: { type: 'Erhvervsgrund' } }
                - { label: 'Betalte Andre grunde', route: 'grundsalg_statistics_betalte_overview', params: { type: 'Andre' } }
                - { label: 'Betalte Pr. område' }
                - { label: 'Parcelhusgrunde pr. område', route: 'grundsalg_statistics_omraade_overview', params: { type: 'Parcelhusgrund' } }
                - { label: 'Storparceller pr. område', route: 'grundsalg_statistics_omraade_overview', params: { type: 'Storparcel' } }
                - { label: 'Erhvervsgrunde pr. område', route: 'grundsalg_statistics_omraade_overview', params: { type: 'Erhvervsgrund' } }
                - { label: 'Andre grunde pr. område', route: 'grundsalg_statistics_omraade_overview', params: { type: 'Andre' } }
                - { label: 'Rapporter', icon: 'table', route: 'grundsalg_report' }
            - { entity: 'interessent', label: 'Interessenter', icon: 'user-circle' }
            - label: 'Log ud'
              icon: 'sign-out'
              route: 'fos_user_security_logout'
